# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cca123c25fb792a28ec2a11fb67f8531aef66a251fa876546c0cb22df277268c20b4f5281015eeeeca199972eb6d6fefa2ae9e5137bc9bdb04b5ac34aca40ffb

test:
  secret_key_base: 299be07cb79d375a615f8a56fc329dfa425560acc56ed736a2c0d5d402f329cdb4f33d331c723357bd8c7b484a1084f4bf82ff9816979f0d95e599b71b345394

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
